### ISSUE TITLE
Books and Music items not displaying on website

### ISSUE THREAD

**Issue by tgilliss** [a8cteam51/onbeing#106]
![screen shot 2017-09-27 at 8 39 09 am](https://user-images.githubusercontent.com/25962042/30916703-aabb3b9a-a35f-11e7-86e4-72f9a8d541fc.png)

The books and music lists for each episode are currently not displaying on the website after activating the accordion functionality. See attached screenshot of https://onbeing.org/programs/arnold-eisen-the-opposite-of-good-is-indifference-sep2017/.

**Comment by michiecat** [comment]
@tgilliss I'm looking into this today.

**Comment by tgilliss** [comment]
Thank you!
T

...................
*Trent Gilliss*
Cofounder + Publisher / Editor-in-Chief
*On Being <https://onbeing.org/> + On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

**Comment by michiecat** [comment]
@tgilliss Just an update, I'm still working to get to the bottom of this. It appears to be a problem with the Amazon Simple Affiliate Shortcode. The same issue is also happening on the test site. Do you recall a time it was working ever since you switched to WordPress? Or is this a recent problem that you noticed? Also, was the accordion functionality something you activated in WP Admin?

**Comment by ChrisHardie** [comment]
@tgilliss following up here, it looks like this may be an issue with the license key in use for the ASA2 plugin and/or the AWS affiliate account itself. When visiting https://onbeing.org/wp-admin/admin.php?page=asa2_setup  I see an error message "License issue: Your ASA 2 license is not valid. Please check the license page." and on  "https://onbeing.org/wp-admin/admin.php?page=asa2_license it notes that it can't determine when the license expires - so maybe it's expired.

I'm also seeing errors in the log at https://onbeing.org/wp-admin/admin.php?page=asa2_log along the lines of "AWS.InvalidAssociate" which seems to point to an issue with the AWS API key that's configured at https://onbeing.org/wp-admin/admin.php?page=asa2_setup.

Could you check at https://getasa2.com/your-account/ and https://affiliate-program.amazon.com/assoc_credentials/home to make sure those keys/licenses are current and active? I believe resolving those issues will help that display function again.

**Comment by tgilliss** [comment]
Hi Chris. I'm trying to wade through the messiness of it all. And I
realized that our Amazon IDs were created from our previous parent company,
so I went through the proper steps to update all Amazon API data, but it
looks like I still need to register the ASA2 plugin information. Could you
take a look and confirm this for me?

Thank you!

**Comment by tgilliss** [comment]
OK. I'm pretty sure everything is resolved now, but I sure would appreciate
you double-checking my efforts!
T

**Comment by ChrisHardie** [comment]
It looks like things are working again! I still see a few Amazon API errors going by in the log at https://onbeing.org/wp-admin/admin.php?page=asa2_log but these may be expected, and don't seem to be affecting the sample pages I'm viewing.

I'll go ahead and close out this issue for now but if you have any further questions or encounter other missing content, just let us know.

**Comment by wrightcj03** [comment]
Hi @tgilliss ,

It looks like the "secret access key" is missing from the admin https://onbeing.org/wp-admin/admin.php?page=asa2_setup which means the books and music entries aren't currently showing. Do you know if this was removed intentionally?

**Comment by tgilliss** [comment]
Hey there. I had input the secret access key when I bought the new license
and the status showed 'connected' but it looks like something got wiped
out. Anyhow, I updated and all is working again... I think.

...................
*Trent Gilliss*
Co-founder + Publisher / Editor-in-Chief
*On Being Studios <https://onbeing.org/>*

mobile 651.206.2022 / twitter @trentgilliss
<http://twitter.com/trentgilliss>

**Comment by wrightcj03** [comment]
@tgilliss confirmed.—the UX is a little bumpy but I do see the books and music there. We'll try to resolve the UX issues on the new site.
